module "helm" {
  source = "../modules/helm"

  cluster_domain                        = var.cluster_domain
  acme_email                            = var.acme_email
  bind_zone                             = var.bind_zone
  bind_tsig_key_name                    = var.bind_tsig_key_name
  bind_tsig_secret                      = var.bind_tsig_secret
  bind_tsig_algorithm                   = var.bind_tsig_algorithm
  grafana_admin_password                = var.grafana_admin_password
  cloudflare_tunnel_token               = var.cloudflare_tunnel_token
  vaultwarden_admin_token               = var.vaultwarden_admin_token
  postfix_enabled                       = var.postfix_enabled
  postfix_extra_allowed_sender_domains  = var.postfix_extra_allowed_sender_domains
  postfix_relayhost                     = var.postfix_relayhost
  postfix_relay_username                = var.postfix_relay_username
  postfix_relay_password                = var.postfix_relay_password
  vaultwarden_smtp_host                 = var.vaultwarden_smtp_host
  vaultwarden_smtp_port                 = var.vaultwarden_smtp_port
  vaultwarden_smtp_security             = var.vaultwarden_smtp_security
  vaultwarden_smtp_username             = var.vaultwarden_smtp_username
  vaultwarden_smtp_password             = var.vaultwarden_smtp_password
  vaultwarden_smtp_from                 = var.vaultwarden_smtp_from
  vaultwarden_smtp_from_name            = var.vaultwarden_smtp_from_name
  vaultwarden_smtp_accept_invalid_certs = var.vaultwarden_smtp_accept_invalid_certs
  wireguard_admin_password_hash         = var.wireguard_admin_password_hash
  wireguard_public_host                 = var.wireguard_public_host
  nexus_admin_password                  = var.nexus_admin_password
  keycloak_admin_password               = var.keycloak_admin_password
  keycloak_postgres_password            = var.keycloak_postgres_password
  keycloak_chart_archive_path           = var.keycloak_chart_archive_path
  registry_htpasswd                     = var.registry_htpasswd
  enable_wazuh                          = var.enable_wazuh
  headlamp_oauth_client_id              = var.headlamp_oauth_client_id
  headlamp_oauth_client_secret          = var.headlamp_oauth_client_secret
  headlamp_oauth_keycloak_realm         = var.headlamp_oauth_keycloak_realm
}