apiVersion: v1
kind: Service
metadata:
  name: {{ include "crm.fullname" . }}-api
spec:
  selector:
    app.kubernetes.io/name: {{ include "crm.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.app.servicePort }}
      targetPort: 8080
