apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crm.fullname" . }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
